index:
    path: /
    controller: App\Controller\DefaultController::index
post_page:
    path: /post/{id}
    controller: App\Controller\DefaultController::showPost
    requirements:
        id: '\d+'